name: Fission
favicon: null
layout_spectrum: 0.8299421847332269
typography_spectrum: 0.6291362312622368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.41767489328049123
  lightness: 0.1419199793599546
  saturation: 0.1782975618261844
  rhythmicContrast: 0.8174705237615854
purpose: []
