name: Fission
favicon: null
layout_spectrum: 0.56624
typography_spectrum: 0.75285
title: Fission
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#766d68'
    - '#ffa901'
    - '#ffffff'
    - '#56afb0'
  brandStrength: 0.4375
  lightness: 0.1419199793599546
  saturation: 0.1782975618261844
  rhythmicContrast: 0.8174705237615854
purpose: []
